In [4]:
import numpy as np

In [10]:
input_data = np.array([1, 2])
target_data = np.array([1])

learning_rate = 1e-1

def numerical_derivative(f, x):
  it = np.nditer(x, flags = ['multi_index'], op_flags=['readwrite'])
  grad = np.zeros_like(x)

  while not it.finished:
    delta_x = 1e-4
    idx = it.multi_index
    tmp_value = x[idx] 
    
    x[idx] = float(x[idx]) + delta_x
    fx1 = f(x)

    x[idx] = tmp_value
    x[idx] = float(x[idx]) - delta_x
    fx2 = f(x)

    grad[idx] = fx1 - fx2 / 2 * delta_x
    x[idx] = tmp_value

    it.iternext

  return grad

def sigmoid(x):
  return 1/ (1 + np.exp(-x))

In [6]:
input_nodes = 2
hidden_nodes = 3
output_nodes = 1

In [7]:
W2 = np.random.rand(input_nodes, hidden_nodes)
b2 = np.random.rand(hidden_nodes,)
W3 = np.random.rand(hidden_nodes, output_nodes)
b3 = np.random.rand(output_nodes,)

In [8]:

def feedforward(xdata):

  Z2 = np.dot(xdata, W2) + b2
  A2 = sigmoid(Z2)

  Z3 = np.dot(A2, W3) + b3
  A3 = sigmoid(Z3)

  Y = A3

  loss = np.sum((target_data - Y)**2) / len(Y)

  return loss

feedforward(input_data)

0.008456491894972783

In [8]:
f = lambda x, y : x**2 + 3 * y
numerical_derivative(f, np.array([1, 2]))

debug 3. idx =  (0,) , x[idx] =  1


TypeError: ignored

In [2]:
import numpy as np

def numerical_derivative(f, x):    
    delta_x = 1e-4 
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])   
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)   # f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x 
        fx2 = f(x)   # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()   
        
    return grad

In [13]:
for i in range(10):

  W2 = W2 - learning_rate * numerical_derivative(feedforward, W2)

  W3 = W3 - learning_rate * numerical_derivative(feedforward, W3)

  b2 = b2 - learning_rate * numerical_derivative(feedforward, b2)

  b3 = b3 - learning_rate * numerical_derivative(feedforward, b3)

ValueError: ignored

In [ ]:
import numpy as np

Y = np.array([0.2, 0.8, 0.1, 0.9, 0.2])

Y.shape

(5,)

In [ ]:
Y.shape == (5,)

True

In [ ]:
Y_COMP = np.argmax(Y)

print(Y_COMP)

3


In [ ]:
T = np.array([0, 1, 2, 3, 4])

In [ ]:
loss = Y_COMP - T

In [ ]:
loss

array([ 3,  2,  1,  0, -1])

In [ ]:
import numpy as np
import tensorflow as tf

T = np.array([0, 1, 2, 3, 4])

In [ ]:
Y_ONEHOT = tf.keras.utils.to_categorical(T, 5)

In [ ]:
print(Y_ONEHOT[1])

[0. 1. 0. 0. 0.]


In [ ]:
import numpy as np

input_data = np.array([[2, 1, 2], [1, 2, 3], [3, 0, 2]])

target_data = np.array([1, 1, 3])

one_hot_encode = np.array([0, 1, 2, 3, 4])

In [ ]:
m = []
xdata = []
for i in range(len(input_data)):
  x_data = []
  for j in input_data[i]:
    k = np.zeros((5,))
    k[j] = 1
    x_data.append(k)
  xdata.append(x_data)
  l = np.zeros((5,))
  l[target_data[i]] = 1
  m.append(l)

tdata = np.array(m)
xdata = np.array(xdata)

In [ ]:
xdata

array([[[0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]],

       [[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.]]])

In [ ]:
tdata

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [ ]:
input = [ [2, 1, 2], [1, 2, 3], [3, 0, 2] ] 
xdata = np.array(input)
label = [1, 1, 3]
tdata = np.zeros((3, 5)) + 0.01
for index in range(len(label)):
  tdata[index, int(label[index])] = 0.99

print(xdata, tdata)

[[2 1 2]
 [1 2 3]
 [3 0 2]] [[0.01 0.99 0.01 0.01 0.01]
 [0.01 0.99 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.99 0.01]]


In [ ]:
W2 = np.random.rand(3,4)
b2 = np.random.rand(4,)

W3 = np.random.rand(4, 5)
b3 = np.random.rand(5,)

A1 = xdata
A2 = sigmoid(np.dot(A1, W2) + b2)
A3 = Y = sigmoid(np.dot(A2, W3) + b3)

for index in Y:
  print(np.argmax(index))

0
0
0


In [ ]:

def predict(test_xdata):
  A1 = test_xdata
  A2 = sigmoid(np.dot(A1, W2) + b2)
  A3 = Y = np.argmax(sigmoid(np.dot(A2, W3) + b3))

  sigmoid_val = sigmoid(np.dot(A2, W3) + b3)

  return Y, sigmoid_val

predicted_num, sigmoid_val = predict(np.array([1,1,2]))
  
print(predicted_num)
print(sigmoid_val.reshape(5,1))

0
[[0.9627648 ]
 [0.95231846]
 [0.85795303]
 [0.87950942]
 [0.93591861]]


In [ ]:
input = [ [2, 1, 2], [1, 2, 3], [3, 0, 2] ] 
label = [1, 1, 3]

tdata = np.zeros((3, 5)) + 0.01
xdata = np.array(input)

for index in range(len(label)):
  tdata[index, label[index]] = 0.99

tdata.shape

array([[0.01, 0.99, 0.01, 0.01, 0.01],
       [0.01, 0.99, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.99, 0.01]])

In [ ]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [ ]:
W2 = np.random.rand(3, 4)
b2 = np.random.rand(4,)

W3 = np.random.rand(4, 5)
b3 = np.random.rand(5,)

A1 = xdata
A2 = sigmoid(np.dot(W2, A1) + b2)
A3 = sigmoid(np.dot(W3, A2) + b3)